<a href="https://colab.research.google.com/github/parisaGBP/MachineLearning2024/blob/main/MiniProject1/MLMiniproject1q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##ML-Mini project1- question2

#.mat to csv

In [ ]:
# https://drive.google.com/file/d/1uHuhbbbg7F4BNSjYr9oZu22KsJyCX7-e/view?usp=drive_link
!gdown 1uHuhbbbg7F4BNSjYr9oZu22KsJyCX7-e

Downloading...
From (original): https://drive.google.com/uc?id=1uHuhbbbg7F4BNSjYr9oZu22KsJyCX7-e
From (redirected): https://drive.google.com/uc?id=1uHuhbbbg7F4BNSjYr9oZu22KsJyCX7-e&confirm=t&uuid=b1828976-132f-4f51-9559-bfcee8efcb34
To: /content/97.mat
100% 3.90M/3.90M [00:00<00:00, 53.7MB/s]

In [ ]:
from scipy.io import loadmat
mat = scipy.io.loadmat('/content/97.mat')
print(mat)

NameError: name 'scipy' is not defined

In [ ]:
print(mat.keys())

dict_keys(['__header__', '__version__', '__globals__', 'X097_DE_time', 'X097_FE_time', 'X097RPM'])

In [ ]:
import pandas as pd
x = mat["X105_DE_time"]
y = mat["X105_FE_time"]
c = mat["X105_BA_time"]
d = mat["X105RPM"]
df = pd.DataFrame(x)
df1 = pd.DataFrame(y)
df2 = pd.DataFrame(c)
df3 = pd.DataFrame(d)

df.to_csv('example.csv', index = False)
df1.to_csv('example1.csv', index = False)
df2.to_csv('example2.csv', index = False)
df3.to_csv('example3.csv', index = False)

In [ ]:
df3 = pd.DataFrame(d)
df3.to_csv('example3.csv', index = False)

#Data

In [ ]:
# https://drive.google.com/file/d/1Is08hcGWu9y3HR-9FFnPCtsmTl_iY5-c/view?usp=sharing
!gdown 1Is08hcGWu9y3HR-9FFnPCtsmTl_iY5-c
# https://drive.google.com/file/d/1fZS_k2GxHAqjtIVYIOP3tSbWztsmH-ne/view?usp=sharing
!gdown 1fZS_k2GxHAqjtIVYIOP3tSbWztsmH-ne

Downloading...
From: https://drive.google.com/uc?id=1Is08hcGWu9y3HR-9FFnPCtsmTl_iY5-c
To: /content/97csv.csv
100% 6.38M/6.38M [00:00<00:00, 67.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1fZS_k2GxHAqjtIVYIOP3tSbWztsmH-ne
To: /content/107csv.csv
100% 4.70M/4.70M [00:00<00:00, 222MB/s]

In [ ]:
import pandas as pd
df = pd.read_csv("/content/97csv.csv")
df

        X097_DE_time  X097_FE_time  X097RPM
0           0.053197      0.145667   1796.0
1           0.088662      0.097796      NaN
2           0.099718      0.054856      NaN
3           0.058621      0.036982      NaN
4          -0.004590      0.054445      NaN
...              ...           ...      ...
243933     -0.059664      0.142791      NaN
243934     -0.063836      0.148955      NaN
243935     -0.034630      0.140531      NaN
243936      0.016689      0.095536      NaN
243937      0.046938      0.090195      NaN

[243938 rows x 3 columns]

In [ ]:
df1 = pd.read_csv("/content/105csv.csv")
df1

        X105_DE_time  X105_FE_time  X105_BA_time  X105RPM
0          -0.083004     -0.402075      0.064661   1797.0
1          -0.195734     -0.004725     -0.023096      NaN
2           0.233419     -0.106631     -0.088522      NaN
3           0.103958     -0.074169     -0.093632      NaN
4          -0.181115      0.208947     -0.076491      NaN
...              ...           ...           ...      ...
121260      0.324545     -0.078484      0.010421      NaN
121261      0.142456     -0.012327      0.038306      NaN
121262     -0.316424      0.315989      0.096489      NaN
121263     -0.063675      0.350916      0.084056      NaN
121264      0.267368      0.033078     -0.020159      NaN

[121265 rows x 4 columns]

In [ ]:
import numpy as np
NormalD = df['X097_DE_time']
FaultD = df1['X105_DE_time']

Window=200
n = 100
NormalMatrix = np.zeros((Window,n))
FaultMatrix = np.zeros((Window,n))

for i in range(n):
  NormalMatrix[:,i] = NormalD[(i*Window):(i*Window + Window)]

for i in range(n):
  FaultMatrix[:,i] = FaultD[(i*Window):(i*Window + Window)]

Normal_labels = np.zeros(n)
fault_labels = np.ones(n)

X = np.hstack((NormalMatrix, FaultMatrix))
y = np.hstack((Normal_labels, fault_labels))

X,y
# NormalMatrix ,FaultMatrix
# X105_DE_time\nmjklbnhjnnnnnnnnnnnnnnnnnm,k[]

#Feature extraction

In [ ]:
import numpy as np

# For each feature we used the given formula
#1. Peak
def calculate_peak(data):
    return np.max(data)

#2.crest_factor
def calculate_crest_factor(data):
    peak = calculate_peak(data)
    rms = np.sqrt(np.mean(np.square(data)))
    return peak / rms

#3.clearance_factor
def calculate_clearance_factor(data):
    peak = calculate_peak(data)
    return peak / (np.max(np.abs(data)))
#4.shape_factor
def calculate_shape_factor(data):
    rms = np.sqrt(np.mean(np.square(data)))
    mean = np.mean(data)
    return rms / mean

#5.mean
def calculate_mean(data):
    return np.mean(data)

#6. absolute_mean
def calculate_absolute_mean(data):
    return np.mean(np.abs(data))

#7.peak_to_peak
def calculate_peak_to_peak(data):
    return np.max(data) - np.min(data)

#8.impact_factor
def calculate_impact_factor(data):
    return np.max(np.abs(data))

n = 100
# A : Normal
Normal_features = []
for i in range(n):
    features = []
    data = NormalMatrix[:, i]
    features.append(calculate_peak(data))
    features.append(calculate_crest_factor(data))
    features.append(calculate_clearance_factor(data))
    features.append(calculate_absolute_mean(data))
    features.append(calculate_mean(data))
    features.append(calculate_shape_factor(data))
    features.append(calculate_peak_to_peak(data))
    features.append(calculate_impact_factor(data))
    Normal_features.append(features)

# B : fault
Fault_features = []
for i in range(n):
    features = []
    data = FaultMatrix[:, i]
    features.append(calculate_peak(data))
    features.append(calculate_crest_factor(data))
    features.append(calculate_clearance_factor(data))
    features.append(calculate_absolute_mean(data))
    features.append(calculate_mean(data))
    features.append(calculate_shape_factor(data))
    features.append(calculate_peak_to_peak(data))
    features.append(calculate_impact_factor(data))
    Fault_features.append(features)

Normal_features = np.array(Normal_features)
fault_features = np.array(Fault_features)

# print("Normal Data features:")
# print(Normal_features)

# print("Fault Data features:")
# print(fault_features)

In [ ]:
# 0 is a lable for normal data and 1 is for fault data
new_dataset = []

for features in Normal_features:
    new_sample = np.append(features, 0)
    new_dataset.append(new_sample)



for features in fault_features:
    new_sample = np.append(features, 1)
    new_dataset.append(new_sample)

new_dataset = np.array(new_dataset)

print("New Dataset:")
print(new_dataset)

New Dataset:
[[0.21779446 2.42548055 1.         ... 0.41639631 0.21779446 0.        ]
 [0.16251139 2.48023789 1.         ... 0.29957169 0.16251139 0.        ]
 [0.19213477 2.37339656 1.         ... 0.37196123 0.19213477 0.        ]
 ...
 [0.91987014 3.36529667 1.         ... 1.76323333 0.91987014 1.        ]
 [1.16433501 3.66284287 1.         ... 2.11376834 1.16433501 1.        ]
 [1.43738846 4.68213956 1.         ... 2.60529705 1.43738846 1.        ]]

In [ ]:
import pandas as pd

new_dataset = pd.DataFrame(new_dataset)
column_names = ["Peak", "crest_factor", "clearance_factor", "shape_factor", "mean", "absolute_mean", "peak_to_peak", "impact_factor", "Label"]
new_dataset.columns = column_names

csv_file_path = "newData.csv"
new_dataset.to_csv(csv_file_path, index=False)

#Shuffle

In [ ]:
dataset = pd.read_csv('newData.csv')

# shuffle
from sklearn.utils import shuffle
dataset = shuffle(dataset, random_state=20)

test/train

In [ ]:
from sklearn.model_selection import train_test_split

X = dataset.drop('Label', axis=1).values
y = dataset['Label'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((160, 8), (160,), (40, 8), (40,))

#MinMaxScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
#train
print(scaler.fit(X_train))
print(scaler.data_max_)
# print(scaler.transform(X_train))
#test
print(scaler.fit(X_test))
print(scaler.data_max_)
# print(scaler.transform(X_test))

MinMaxScaler()
[1.58455469e+00 4.97563360e+00 1.00000000e+00 2.42727627e-01
 2.46739846e-02 9.94696931e+01 2.73345836e+00 1.58455469e+00]
MinMaxScaler()
[1.56571222e+00 4.91864850e+00 1.00000000e+00 2.39837093e-01
 2.03514739e-02 3.01857732e+01 2.66101230e+00 1.56571222e+00]

In [ ]:
print(scaler.transform(X_train))

[[ 0.5655685   0.38983886  1.         ...  0.58745483  0.67758139
   0.5655685 ]
 [-0.00486062 -0.04188475  0.15355713 ...  0.15654071  0.02315505
   0.0260706 ]
 [ 0.69172337  0.7261817   1.         ...  0.56873094  0.78568926
   0.69172337]
 ...
 [ 0.03520267  0.27073032  1.         ...  0.01010863  0.01144646
   0.03520267]
 [ 0.01973706  0.20885623  1.         ...  0.0153479   0.00314559
   0.01973706]
 [ 0.75216302  0.65560829  1.         ...  0.57135513  0.82038719
   0.75216302]]

In [ ]:
(scaler.transform(X_test))

array([[0.02400852, 0.1675707 , 1.        , 0.07164686, 0.39741329,
        0.12304813, 0.03206755, 0.02400852],
       [0.71408719, 0.72554454, 1.        , 0.76295718, 0.55120204,
        0.66809958, 0.75337256, 0.71408719],
       [1.        , 0.97296533, 1.        , 0.91447942, 0.7789586 ,
        0.58937276, 1.        , 1.        ],
       [0.02106269, 0.10998512, 1.        , 0.09395508, 0.56496179,
        0.0817034 , 0.03556265, 0.02106269],
       [0.02341935, 0.1654395 , 1.        , 0.06942933, 0.29740675,
        0.16686677, 0.03634905, 0.02341935],
       [0.00736458, 0.18770514, 1.        , 0.03151866, 0.32921811,
        0.10984299, 0.01092219, 0.00736458],
       [0.85538064, 0.71164634, 1.        , 1.        , 0.58517734,
        0.77767841, 0.90019242, 0.85538064],
       [0.04433474, 0.2159968 , 0.19921659, 0.08891379, 0.13423476,
        0.326957  , 0.08860082, 0.08719657],
       [0.9991972 , 1.        , 1.        , 0.92130732, 0.89660061,
        0.50626221, 0.97836482, 0.9991972 ],
       [0.        , 0.18731581, 1.        , 0.02365362, 0.04356914,
        0.29660998, 0.        , 0.        ],
       [0.52703392, 0.51704301, 1.        , 0.71939775, 0.73847306,
        0.45731199, 0.61070283, 0.52703392],
       [0.69046182, 0.65759792, 0.85323811, 0.80339872, 0.86038741,
        0.4617152 , 0.84984641, 0.72429427],
       [0.99300414, 0.95708973, 1.        , 0.91788715, 0.61279498,
        0.72700469, 0.99169971, 0.99300414],
       [0.64756917, 0.54337885, 1.        , 0.87083717, 0.75535899,
        0.54344918, 0.69146056, 0.64756917],
       [0.94850588, 0.9167702 , 1.        , 0.95843221, 0.73689637,
        0.60914773, 0.92829094, 0.94850588],
       [0.66110214, 0.87768123, 1.        , 0.61974933, 0.66441912,
        0.46315154, 0.62369755, 0.66110214],
       [0.02445039, 0.04271096, 0.98779866, 0.12730307, 0.64158338,
        0.08710159, 0.03984415, 0.02489226],
       [0.01163603, 0.        , 0.63761722, 0.12207566, 0.79672088,
        0.04725173, 0.03215493, 0.02474497],
       [0.02165185, 0.07122048, 0.        , 0.10582443, 0.35266837,
        0.16934439, 0.06527102, 0.07055263],
       [0.71144941, 0.69006767, 1.        , 0.81550178, 0.71650101,
        0.54949954, 0.76051625, 0.71144941],
       [0.71661029, 0.56426435, 1.        , 0.97152074, 0.65383999,
        0.67240923, 0.77078956, 0.71661029],
       [0.68277785, 0.56776053, 1.        , 0.86354966, 0.73084388,
        0.57837091, 0.7288799 , 0.68277785],
       [0.54400749, 0.46102267, 1.        , 0.76112702, 0.85565732,
        0.43643235, 0.62396969, 0.54400749],
       [0.00898478, 0.15168014, 1.        , 0.04265948, 0.65588869,
        0.03413012, 0.00332035, 0.00898478],
       [0.04448204, 0.05213274, 1.        , 0.18093319, 0.43693252,
        0.18919014, 0.06160116, 0.04448204],
       [0.52118493, 0.47350313, 0.82394592, 0.79820637, 0.71929838,
        0.48504366, 0.64805413, 0.55341176],
       [0.70560041, 0.52688629, 0.81737285, 0.91555598, 0.84772297,
        0.54454877, 0.87345461, 0.74895181],
       [0.02533414, 0.25863425, 1.        , 0.04375495, 0.91704226,
        0.        , 0.01223285, 0.02533414],
       [0.02975288, 0.15859802, 1.        , 0.09849117, 0.4055131 ,
        0.13388427, 0.03433937, 0.02975288],
       [0.66706583, 0.52907565, 1.        , 0.90292706, 0.72341814,
        0.59133341, 0.75276024, 0.66706583],
       [0.01841144, 0.10785075, 0.88002006, 0.09716703, 0.82232674,
        0.02876294, 0.03495101, 0.02268289],
       [0.04698599, 0.20701911, 0.68287245, 0.10077783, 0.        ,
        0.56988765, 0.0750573 , 0.06171514],
       [0.57439934, 0.4622028 , 0.95148091, 0.81834226, 0.59016174,
        0.64464318, 0.69758373, 0.58368893],
       [0.0276908 , 0.15572575, 1.        , 0.07087046, 0.52452805,
        0.09170717, 0.04272761, 0.0276908 ],
       [0.03152038, 0.20299728, 1.        , 0.08233034, 1.        ,
        0.0051164 , 0.04482467, 0.03152038],
       [0.01767498, 0.39251122, 1.        , 0.        , 0.23809524,
        0.12090375, 0.00515527, 0.01767498],
       [0.76042043, 0.64137701, 1.        , 0.93364639, 0.58827987,
        0.72745285, 0.812291  , 0.76042043],
       [0.84735261, 0.83164963, 1.        , 0.88773922, 0.35701389,
        1.        , 0.87862528, 0.84735261],
       [0.59515755, 0.76100236, 1.        , 0.64549163, 0.71512776,
        0.425163  , 0.55783951, 0.59515755],
       [0.03284601, 0.16845712, 1.        , 0.09944837, 0.21542883,
        0.24089167, 0.03643643, 0.03284601]])

In [ ]:
X_test_minmax = scaler.fit_transform(X_test)
X_train_minmax = scaler.fit_transform(X_train)

X_train_minmax.shape, X_test_minmax.shape, y_train.shape, y_test.shape

((160, 8), (40, 8), (160,), (40,))

Logistic Regression

In [ ]:
#Logistic Regression (from Scratch)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def logistic_regression(x, w):
    y_hat = sigmoid(x @ w)
    return y_hat

#Binary Cross Entropy (BCE)

def bce(y, y_hat):
    loss = -(np.mean(y*np.log(y_hat) + (1-y)*np.log(1-y_hat)))
    return loss

Gradient

In [ ]:
#Gradient
def gradient(x, y, y_hat):
    grads = (x.T @ (y_hat - y)) / len(y)
    return grads


#Gradient Descent

def gradient_descent(w, eta, grads):
    w = w - eta*grads
    # w -= eta*grads
    return w

Accuracy

In [ ]:
#Accuracy

def accuracy(y, y_hat):
    acc = np.sum(y == np.round(y_hat)) / len(y)
    return acc

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
#hyper parameter
m = 7
w = np.random.randn(m+1, 1)
print(w.shape)
eta = 0.01
n_epochs = 2000

# X_train_minmax = np.hstack((np.ones((len(X_train_minmax), 1)), X_train_minmax))
print(X_train_minmax.shape)

error_hist = []

for epoch in range(n_epochs):
    # predictions
    y_hat = logistic_regression(X_train_minmax, w)

    # loss
    e = bce(y_train, y_hat)
    error_hist.append(e)

    # gradients
    grads = gradient(X_train_minmax, y_train, y_hat)

    # gradient descent

    w = gradient_descent(w, eta, grads)

    if (epoch+1) % 1 == 0:
        print(f'Epoch={epoch}, \t E={e:.4},\t w={w.T[0]}')

(8, 1)
(160, 8)
Epoch=0, 	 E=0.9505,	 w=[-0.677891   -1.09107642 -0.86100846  0.65463398  1.52254012 -1.14252556
 -0.63455977 -1.11290914]
Epoch=1, 	 E=0.9439,	 w=[-0.6783831  -1.09182235 -0.86340618  0.65390044  1.52111146 -1.14275804
 -0.63514739 -1.11341436]
Epoch=2, 	 E=0.9373,	 w=[-0.67887313 -1.09256583 -0.86579776  0.65316968  1.51968647 -1.14298985
 -0.63573265 -1.1139175 ]
Epoch=3, 	 E=0.9307,	 w=[-0.67936112 -1.09330687 -0.86818322  0.6524417   1.51826513 -1.14322099
 -0.63631557 -1.11441856]
Epoch=4, 	 E=0.9242,	 w=[-0.67984708 -1.09404548 -0.8705626   0.65171648  1.51684742 -1.14345146
 -0.63689618 -1.11491757]
Epoch=5, 	 E=0.9177,	 w=[-0.68033103 -1.09478167 -0.87293593  0.65099399  1.51543332 -1.14368127
 -0.63747447 -1.11541454]
Epoch=6, 	 E=0.9112,	 w=[-0.68081297 -1.09551547 -0.87530322  0.65027422  1.51402281 -1.14391042
 -0.63805048 -1.11590947]
Epoch=7, 	 E=0.9048,	 w=[-0.68129292 -1.09624688 -0.87766452  0.64955716  1.51261588 -1.14413892
 -0.6386242  -1.11640239]
Epoch=8, 	 E=0.8985,	 w=[-0.68177089 -1.09697592 -0.88001986  0.64884279  1.51121251 -1.14436677
 -0.63919567 -1.1168933 ]
Epoch=9, 	 E=0.8921,	 w=[-0.68224691 -1.0977026  -0.88236925  0.64813108  1.50981269 -1.14459398
 -0.63976489 -1.11738222]
Epoch=10, 	 E=0.8858,	 w=[-0.68272097 -1.09842695 -0.88471273  0.64742202  1.50841639 -1.14482054
 -0.64033188 -1.11786917]
Epoch=11, 	 E=0.8796,	 w=[-0.68319309 -1.09914896 -0.88705033  0.6467156   1.5070236  -1.14504646
 -0.64089665 -1.11835415]
Epoch=12, 	 E=0.8734,	 w=[-0.68366329 -1.09986865 -0.88938208  0.6460118   1.5056343  -1.14527175
 -0.64145922 -1.11883718]
Epoch=13, 	 E=0.8672,	 w=[-0.68413158 -1.10058604 -0.89170799  0.6453106   1.50424848 -1.1454964
 -0.6420196  -1.11931828]
Epoch=14, 	 E=0.8611,	 w=[-0.68459796 -1.10130115 -0.89402811  0.64461199  1.50286611 -1.14572043
 -0.6425778  -1.11979744]
Epoch=15, 	 E=0.855,	 w=[-0.68506246 -1.10201398 -0.89634246  0.64391595  1.50148719 -1.14594383
 -0.64313384 -1.1202747 ]
Epoch=16, 	 E=0.8489,	 w=[-0.68552509 -1.10272454 -0.89865106  0.64322246  1.5001117  -1.14616662
 -0.64368774 -1.12075005]
Epoch=17, 	 E=0.8429,	 w=[-0.68598585 -1.10343286 -0.90095395  0.64253151  1.49873961 -1.14638878
 -0.6442395  -1.12122352]
Epoch=18, 	 E=0.837,	 w=[-0.68644477 -1.10413894 -0.90325114  0.64184309  1.49737092 -1.14661034
 -0.64478915 -1.12169511]
Epoch=19, 	 E=0.831,	 w=[-0.68690184 -1.10484279 -0.90554267  0.64115716  1.4960056  -1.14683128
 -0.64533668 -1.12216483]
Epoch=20, 	 E=0.8252,	 w=[-0.68735709 -1.10554443 -0.90782856  0.64047373  1.49464365 -1.14705162
 -0.64588213 -1.12263271]
Epoch=21, 	 E=0.8193,	 w=[-0.68781052 -1.10624388 -0.91010884  0.63979278  1.49328504 -1.14727136
 -0.64642549 -1.12309874]
Epoch=22, 	 E=0.8135,	 w=[-0.68826215 -1.10694114 -0.91238354  0.63911429  1.49192976 -1.14749049
 -0.64696679 -1.12356295]
Epoch=23, 	 E=0.8077,	 w=[-0.68871199 -1.10763622 -0.91465268  0.63843824  1.4905778  -1.14770903
 -0.64750604 -1.12402534]
Epoch=24, 	 E=0.802,	 w=[-0.68916005 -1.10832914 -0.91691629  0.63776462  1.48922914 -1.14792698
 -0.64804324 -1.12448593]
Epoch=25, 	 E=0.7963,	 w=[-0.68960634 -1.10901992 -0.91917439  0.63709342  1.48788376 -1.14814434
 -0.64857842 -1.12494472]
Epoch=26, 	 E=0.7907,	 w=[-0.69005088 -1.10970855 -0.921427    0.63642462  1.48654165 -1.14836112
 -0.64911159 -1.12540174]
Epoch=27, 	 E=0.7851,	 w=[-0.69049367 -1.11039506 -0.92367416  0.6357582   1.48520279 -1.14857731
 -0.64964275 -1.12585698]
Epoch=28, 	 E=0.7796,	 w=[-0.69093472 -1.11107946 -0.92591589  0.63509416  1.48386717 -1.14879292
 -0.65017192 -1.12631047]
Epoch=29, 	 E=0.774,	 w=[-0.69137405 -1.11176176 -0.92815221  0.63443247  1.48253477 -1.14900796
 -0.65069912 -1.1267622 ]
Epoch=30, 	 E=0.7686,	 w=[-0.69181167 -1.11244197 -0.93038315  0.63377313  1.48120558 -1.14922242
 -0.65122435 -1.1272122 ]
Epoch=31, 	 E=0.7631,	 w=[-0.69224759 -1.11312009 -0.93260874  0.63311611  1.47987959 -1.14943632
 -0.65174763 -1.12766048]
Epoch=32, 	 E=0.7577,	 w=[-0.69268181 -1.11379616 -0.93482899  0.63246141  1.47855677 -1.14964965
 -0.65226897 -1.12810704]
Epoch=33, 	 E=0.7524,	 w=[-0.69311436 -1.11447016 -0.93704393  0.63180901  1.47723712 -1.14986242
 -0.65278838 -1.12855189]
Epoch=34, 	 E=0.7471,	 w=[-0.69354524 -1.11514213 -0.93925359  0.6311589   1.47592062 -1.15007462
 -0.65330588 -1.12899506]
Epoch=35, 	 E=0.7418,	 w=[-0.69397445 -1.11581206 -0.94145798  0.63051106  1.47460725 -1.15028627
 -0.65382147 -1.12943654]
Epoch=36, 	 E=0.7366,	 w=[-0.69440202 -1.11647997 -0.94365714  0.62986548  1.47329701 -1.15049737
 -0.65433517 -1.12987635]
Epoch=37, 	 E=0.7314,	 w=[-0.69482795 -1.11714586 -0.94585109  0.62922214  1.47198987 -1.15070792
 -0.65484699 -1.1303145 ]
Epoch=38, 	 E=0.7263,	 w=[-0.69525225 -1.11780976 -0.94803985  0.62858104  1.47068583 -1.15091792
 -0.65535694 -1.13075099]
Epoch=39, 	 E=0.7212,	 w=[-0.69567493 -1.11847168 -0.95022344  0.62794216  1.46938486 -1.15112737
 -0.65586503 -1.13118585]
Epoch=40, 	 E=0.7161,	 w=[-0.69609601 -1.11913161 -0.95240189  0.62730548  1.46808696 -1.15133628
 -0.65637127 -1.13161907]
Epoch=41, 	 E=0.7111,	 w=[-0.69651549 -1.11978958 -0.95457522  0.626671    1.46679211 -1.15154466
 -0.65687568 -1.13205068]
Epoch=42, 	 E=0.7061,	 w=[-0.69693338 -1.12044559 -0.95674345  0.6260387   1.4655003  -1.1517525
 -0.65737827 -1.13248067]
Epoch=43, 	 E=0.7012,	 w=[-0.69734969 -1.12109966 -0.95890661  0.62540856  1.46421152 -1.15195981
 -0.65787904 -1.13290907]
Epoch=44, 	 E=0.6963,	 w=[-0.69776443 -1.12175179 -0.96106472  0.62478058  1.46292574 -1.15216658
 -0.65837801 -1.13333587]
Epoch=45, 	 E=0.6914,	 w=[-0.69817761 -1.122402   -0.9632178   0.62415474  1.46164296 -1.15237284
 -0.65887519 -1.13376109]
Epoch=46, 	 E=0.6866,	 w=[-0.69858925 -1.12305029 -0.96536587  0.62353103  1.46036317 -1.15257856
 -0.65937058 -1.13418474]
Epoch=47, 	 E=0.6818,	 w=[-0.69899934 -1.12369668 -0.96750895  0.62290944  1.45908634 -1.15278377
 -0.65986421 -1.13460683]
Epoch=48, 	 E=0.6771,	 w=[-0.69940791 -1.12434118 -0.96964707  0.62228995  1.45781248 -1.15298846
 -0.66035608 -1.13502737]
Epoch=49, 	 E=0.6724,	 w=[-0.69981495 -1.12498379 -0.97178025  0.62167255  1.45654155 -1.15319263
 -0.6608462  -1.13544636]
Epoch=50, 	 E=0.6677,	 w=[-0.70022048 -1.12562453 -0.97390852  0.62105723  1.45527356 -1.15339629
 -0.66133458 -1.13586382]
Epoch=51, 	 E=0.6631,	 w=[-0.70062451 -1.1262634  -0.97603188  0.62044399  1.45400849 -1.15359944
 -0.66182124 -1.13627976]
Epoch=52, 	 E=0.6585,	 w=[-0.70102704 -1.12690043 -0.97815037  0.61983279  1.45274632 -1.15380208
 -0.66230618 -1.13669418]
Epoch=53, 	 E=0.654,	 w=[-0.7014281  -1.1275356  -0.980264    0.61922365  1.45148705 -1.15400422
 -0.66278941 -1.1371071 ]
Epoch=54, 	 E=0.6495,	 w=[-0.70182767 -1.12816895 -0.9823728   0.61861653  1.45023065 -1.15420586
 -0.66327094 -1.13751852]
Epoch=55, 	 E=0.6451,	 w=[-0.70222578 -1.12880047 -0.98447678  0.61801143  1.44897713 -1.154407
 -0.66375079 -1.13792845]
Epoch=56, 	 E=0.6406,	 w=[-0.70262243 -1.12943017 -0.98657598  0.61740835  1.44772646 -1.15460764
 -0.66422896 -1.13833691]
Epoch=57, 	 E=0.6363,	 w=[-0.70301763 -1.13005808 -0.9886704   0.61680726  1.44647863 -1.15480778
 -0.66470546 -1.13874389]
Epoch=58, 	 E=0.6319,	 w=[-0.7034114  -1.13068418 -0.99076007  0.61620816  1.44523363 -1.15500744
 -0.66518031 -1.13914941]
Epoch=59, 	 E=0.6276,	 w=[-0.70380373 -1.1313085  -0.99284501  0.61561103  1.44399145 -1.15520661
 -0.6656535  -1.13955348]
Epoch=60, 	 E=0.6234,	 w=[-0.70419463 -1.13193104 -0.99492524  0.61501586  1.44275207 -1.15540529
 -0.66612506 -1.13995611]
Epoch=61, 	 E=0.6192,	 w=[-0.70458413 -1.13255181 -0.99700078  0.61442265  1.44151549 -1.15560349
 -0.666595   -1.14035731]
Epoch=62, 	 E=0.615,	 w=[-0.70497221 -1.13317083 -0.99907165  0.61383138  1.44028169 -1.15580121
 -0.66706331 -1.14075707]
Epoch=63, 	 E=0.6108,	 w=[-0.7053589  -1.13378809 -1.00113787  0.61324204  1.43905066 -1.15599845
 -0.66753001 -1.14115542]
Epoch=64, 	 E=0.6067,	 w=[-0.7057442  -1.13440362 -1.00319946  0.61265462  1.43782239 -1.15619521
 -0.66799512 -1.14155236]
Epoch=65, 	 E=0.6027,	 w=[-0.70612812 -1.13501741 -1.00525644  0.61206911  1.43659687 -1.1563915
 -0.66845863 -1.1419479 ]
Epoch=66, 	 E=0.5986,	 w=[-0.70651067 -1.13562949 -1.00730883  0.61148549  1.43537408 -1.15658732
 -0.66892056 -1.14234204]
Epoch=67, 	 E=0.5946,	 w=[-0.70689185 -1.13623984 -1.00935665  0.61090377  1.43415401 -1.15678267
 -0.66938092 -1.1427348 ]
Epoch=68, 	 E=0.5907,	 w=[-0.70727167 -1.1368485  -1.01139992  0.61032391  1.43293665 -1.15697756
 -0.66983972 -1.14312618]
Epoch=69, 	 E=0.5868,	 w=[-0.70765014 -1.13745545 -1.01343866  0.60974593  1.43172199 -1.15717198
 -0.67029696 -1.1435162 ]
Epoch=70, 	 E=0.5829,	 w=[-0.70802727 -1.13806072 -1.01547288  0.6091698   1.43051002 -1.15736594
 -0.67075265 -1.14390485]
Epoch=71, 	 E=0.579,	 w=[-0.70840307 -1.13866431 -1.01750261  0.60859552  1.42930073 -1.15755944
 -0.67120681 -1.14429215]
Epoch=72, 	 E=0.5752,	 w=[-0.70877755 -1.13926623 -1.01952786  0.60802307  1.4280941  -1.15775248
 -0.67165945 -1.14467811]
Epoch=73, 	 E=0.5715,	 w=[-0.7091507  -1.13986649 -1.02154865  0.60745244  1.42689013 -1.15794507
 -0.67211056 -1.14506273]
Epoch=74, 	 E=0.5677,	 w=[-0.70952255 -1.1404651  -1.02356501  0.60688363  1.4256888  -1.15813721
 -0.67256016 -1.14544602]
Epoch=75, 	 E=0.564,	 w=[-0.70989309 -1.14106205 -1.02557695  0.60631663  1.4244901  -1.1583289
 -0.67300827 -1.14582799]
Epoch=76, 	 E=0.5604,	 w=[-0.71026234 -1.14165738 -1.02758448  0.60575142  1.42329402 -1.15852014
 -0.67345487 -1.14620864]
Epoch=77, 	 E=0.5567,	 w=[-0.7106303  -1.14225107 -1.02958763  0.60518799  1.42210056 -1.15871094
 -0.6739     -1.14658799]
Epoch=78, 	 E=0.5532,	 w=[-0.71099698 -1.14284314 -1.03158642  0.60462634  1.42090969 -1.15890129
 -0.67434364 -1.14696603]
Epoch=79, 	 E=0.5496,	 w=[-0.71136238 -1.14343361 -1.03358086  0.60406646  1.41972141 -1.15909121
 -0.67478582 -1.14734279]
Epoch=80, 	 E=0.5461,	 w=[-0.71172652 -1.14402246 -1.03557098  0.60350833  1.41853571 -1.15928068
 -0.67522654 -1.14771826]
Epoch=81, 	 E=0.5426,	 w=[-0.71208941 -1.14460972 -1.03755678  0.60295195  1.41735257 -1.15946972
 -0.67566581 -1.14809246]
Epoch=82, 	 E=0.5391,	 w=[-0.71245104 -1.1451954  -1.03953829  0.6023973   1.41617199 -1.15965832
 -0.67610363 -1.14846539]
Epoch=83, 	 E=0.5357,	 w=[-0.71281143 -1.14577949 -1.04151552  0.60184438  1.41499396 -1.1598465
 -0.67654002 -1.14883705]
Epoch=84, 	 E=0.5323,	 w=[-0.71317058 -1.14636201 -1.04348849  0.60129318  1.41381846 -1.16003424
 -0.67697499 -1.14920746]
Epoch=85, 	 E=0.529,	 w=[-0.7135285  -1.14694296 -1.04545723  0.60074369  1.41264549 -1.16022156
 -0.67740853 -1.14957662]
Epoch=86, 	 E=0.5256,	 w=[-0.7138852  -1.14752236 -1.04742174  0.6001959   1.41147503 -1.16040845
 -0.67784066 -1.14994454]
Epoch=87, 	 E=0.5224,	 w=[-0.71424068 -1.1481002  -1.04938204  0.59964979  1.41030708 -1.16059492
 -0.67827139 -1.15031123]
Epoch=88, 	 E=0.5191,	 w=[-0.71459495 -1.14867651 -1.05133816  0.59910537  1.40914162 -1.16078096
 -0.67870072 -1.15067669]
Epoch=89, 	 E=0.5159,	 w=[-0.71494802 -1.14925128 -1.0532901   0.59856262  1.40797864 -1.16096659
 -0.67912866 -1.15104093]
Epoch=90, 	 E=0.5127,	 w=[-0.7152999  -1.14982452 -1.05523789  0.59802153  1.40681814 -1.1611518
 -0.67955523 -1.15140395]
Epoch=91, 	 E=0.5095,	 w=[-0.71565058 -1.15039625 -1.05718154  0.5974821   1.4056601  -1.1613366
 -0.67998042 -1.15176577]
Epoch=92, 	 E=0.5064,	 w=[-0.71600008 -1.15096646 -1.05912107  0.59694431  1.40450451 -1.16152098
 -0.68040424 -1.15212639]
Epoch=93, 	 E=0.5033,	 w=[-0.71634841 -1.15153517 -1.06105649  0.59640816  1.40335137 -1.16170495
 -0.68082671 -1.15248582]
Epoch=94, 	 E=0.5002,	 w=[-0.71669557 -1.15210238 -1.06298782  0.59587364  1.40220066 -1.16188852
 -0.68124783 -1.15284406]
Epoch=95, 	 E=0.4972,	 w=[-0.71704157 -1.1526681  -1.06491509  0.59534073  1.40105237 -1.16207167
 -0.6816676  -1.15320112]
Epoch=96, 	 E=0.4942,	 w=[-0.71738641 -1.15323234 -1.06683829  0.59480944  1.3999065  -1.16225443
 -0.68208604 -1.153557  ]
Epoch=97, 	 E=0.4912,	 w=[-0.7177301  -1.1537951  -1.06875746  0.59427975  1.39876304 -1.16243678
 -0.68250315 -1.15391172]
Epoch=98, 	 E=0.4883,	 w=[-0.71807265 -1.15435639 -1.0706726   0.59375165  1.39762197 -1.16261872
 -0.68291894 -1.15426528]
Epoch=99, 	 E=0.4853,	 w=[-0.71841406 -1.15491622 -1.07258374  0.59322513  1.39648328 -1.16280027
 -0.68333341 -1.15461769]
Epoch=100, 	 E=0.4825,	 w=[-0.71875434 -1.1554746  -1.07449089  0.5927002   1.39534697 -1.16298143
 -0.68374658 -1.15496895]
Epoch=101, 	 E=0.4796,	 w=[-0.71909349 -1.15603153 -1.07639406  0.59217683  1.39421303 -1.16316218
 -0.68415845 -1.15531907]
Epoch=102, 	 E=0.4768,	 w=[-0.71943153 -1.15658702 -1.07829326  0.59165502  1.39308144 -1.16334255
 -0.68456902 -1.15566805]
Epoch=103, 	 E=0.474,	 w=[-0.71976845 -1.15714107 -1.08018853  0.59113477  1.3919522  -1.16352252
 -0.68497831 -1.1560159 ]
Epoch=104, 	 E=0.4712,	 w=[-0.72010427 -1.1576937  -1.08207987  0.59061606  1.3908253  -1.1637021
 -0.68538632 -1.15636263]
Epoch=105, 	 E=0.4685,	 w=[-0.72043899 -1.15824491 -1.08396729  0.59009888  1.38970073 -1.1638813
 -0.68579306 -1.15670825]
Epoch=106, 	 E=0.4657,	 w=[-0.72077262 -1.1587947  -1.08585081  0.58958323  1.38857847 -1.16406011
 -0.68619853 -1.15705275]
Epoch=107, 	 E=0.4631,	 w=[-0.72110515 -1.15934309 -1.08773046  0.5890691   1.38745853 -1.16423853
 -0.68660275 -1.15739615]
Epoch=108, 	 E=0.4604,	 w=[-0.72143661 -1.15989007 -1.08960623  0.58855649  1.38634089 -1.16441658
 -0.68700571 -1.15773845]
Epoch=109, 	 E=0.4578,	 w=[-0.72176699 -1.16043566 -1.09147815  0.58804538  1.38522554 -1.16459424
 -0.68740743 -1.15807966]
Epoch=110, 	 E=0.4551,	 w=[-0.72209629 -1.16097987 -1.09334624  0.58753577  1.38411248 -1.16477153
 -0.68780791 -1.15841978]
Epoch=111, 	 E=0.4526,	 w=[-0.72242454 -1.16152269 -1.0952105   0.58702764  1.38300169 -1.16494844
 -0.68820715 -1.15875882]
Epoch=112, 	 E=0.45,	 w=[-0.72275172 -1.16206414 -1.09707096  0.586521    1.38189317 -1.16512497
 -0.68860517 -1.15909679]
Epoch=113, 	 E=0.4475,	 w=[-0.72307785 -1.16260423 -1.09892762  0.58601583  1.3807869  -1.16530113
 -0.68900198 -1.15943368]
Epoch=114, 	 E=0.445,	 w=[-0.72340293 -1.16314295 -1.1007805   0.58551212  1.37968288 -1.16547692
 -0.68939757 -1.15976952]
Epoch=115, 	 E=0.4425,	 w=[-0.72372697 -1.16368031 -1.10262962  0.58500988  1.3785811  -1.16565234
 -0.68979195 -1.16010429]
Epoch=116, 	 E=0.44,	 w=[-0.72404998 -1.16421633 -1.104475    0.58450908  1.37748155 -1.16582739
 -0.69018513 -1.16043802]
Epoch=117, 	 E=0.4376,	 w=[-0.72437195 -1.164751   -1.10631663  0.58400973  1.37638422 -1.16600208
 -0.69057712 -1.16077069]
Epoch=118, 	 E=0.4352,	 w=[-0.7246929  -1.16528434 -1.10815455  0.58351182  1.37528911 -1.1661764
 -0.69096793 -1.16110233]
Epoch=119, 	 E=0.4328,	 w=[-0.72501283 -1.16581635 -1.10998876  0.58301534  1.3741962  -1.16635036
 -0.69135755 -1.16143293]
Epoch=120, 	 E=0.4305,	 w=[-0.72533174 -1.16634703 -1.11181928  0.58252027  1.37310549 -1.16652396
 -0.69174599 -1.1617625 ]
Epoch=121, 	 E=0.4281,	 w=[-0.72564964 -1.16687639 -1.11364613  0.58202663  1.37201696 -1.1666972
 -0.69213327 -1.16209105]
Epoch=122, 	 E=0.4258,	 w=[-0.72596654 -1.16740444 -1.1154693   0.58153439  1.37093062 -1.16687008
 -0.69251939 -1.16241857]
Epoch=123, 	 E=0.4235,	 w=[-0.72628245 -1.16793119 -1.11728883  0.58104355  1.36984644 -1.1670426
 -0.69290434 -1.16274509]
Epoch=124, 	 E=0.4213,	 w=[-0.72659735 -1.16845664 -1.11910473  0.5805541   1.36876443 -1.16721477
 -0.69328815 -1.16307059]
Epoch=125, 	 E=0.419,	 w=[-0.72691127 -1.16898079 -1.120917    0.58006604  1.36768457 -1.16738659
 -0.69367081 -1.16339509]
Epoch=126, 	 E=0.4168,	 w=[-0.72722421 -1.16950365 -1.12272566  0.57957937  1.36660687 -1.16755805
 -0.69405233 -1.1637186 ]
Epoch=127, 	 E=0.4146,	 w=[-0.72753617 -1.17002523 -1.12453073  0.57909406  1.36553129 -1.16772917
 -0.69443272 -1.16404111]
Epoch=128, 	 E=0.4124,	 w=[-0.72784716 -1.17054554 -1.12633222  0.57861012  1.36445785 -1.16789994
 -0.69481199 -1.16436263]
Epoch=129, 	 E=0.4103,	 w=[-0.72815718 -1.17106457 -1.12813014  0.57812754  1.36338653 -1.16807036
 -0.69519013 -1.16468317]
Epoch=130, 	 E=0.4081,	 w=[-0.72846623 -1.17158234 -1.1299245   0.57764631  1.36231733 -1.16824044
 -0.69556715 -1.16500273]
Epoch=131, 	 E=0.406,	 w=[-0.72877433 -1.17209885 -1.13171533  0.57716643  1.36125023 -1.16841017
 -0.69594307 -1.16532132]
Epoch=132, 	 E=0.4039,	 w=[-0.72908148 -1.1726141  -1.13350262  0.57668788  1.36018523 -1.16857956
 -0.69631788 -1.16563895]
Epoch=133, 	 E=0.4019,	 w=[-0.72938768 -1.17312811 -1.13528641  0.57621067  1.35912232 -1.16874861
 -0.69669159 -1.16595561]
Epoch=134, 	 E=0.3998,	 w=[-0.72969293 -1.17364087 -1.13706669  0.57573478  1.35806149 -1.16891733
 -0.6970642  -1.16627132]
Epoch=135, 	 E=0.3978,	 w=[-0.72999725 -1.1741524  -1.13884348  0.57526022  1.35700274 -1.1690857
 -0.69743573 -1.16658607]
Epoch=136, 	 E=0.3958,	 w=[-0.73030064 -1.17466269 -1.1406168   0.57478697  1.35594606 -1.16925374
 -0.69780618 -1.16689987]
Epoch=137, 	 E=0.3938,	 w=[-0.7306031  -1.17517176 -1.14238666  0.57431502  1.35489143 -1.16942145
 -0.69817555 -1.16721273]
Epoch=138, 	 E=0.3918,	 w=[-0.73090463 -1.17567961 -1.14415306  0.57384437  1.35383886 -1.16958882
 -0.69854385 -1.16752466]
Epoch=139, 	 E=0.3899,	 w=[-0.73120524 -1.17618624 -1.14591603  0.57337502  1.35278833 -1.16975587
 -0.69891108 -1.16783565]
Epoch=140, 	 E=0.3879,	 w=[-0.73150494 -1.17669166 -1.14767558  0.57290695  1.35173983 -1.16992258
 -0.69927726 -1.16814571]
Epoch=141, 	 E=0.386,	 w=[-0.73180374 -1.17719588 -1.14943171  0.57244017  1.35069337 -1.17008896
 -0.69964237 -1.16845485]
Epoch=142, 	 E=0.3841,	 w=[-0.73210162 -1.1776989  -1.15118445  0.57197466  1.34964892 -1.17025502
 -0.70000644 -1.16876308]
Epoch=143, 	 E=0.3822,	 w=[-0.73239861 -1.17820072 -1.1529338   0.57151042  1.34860649 -1.17042075
 -0.70036946 -1.16907038]
Epoch=144, 	 E=0.3804,	 w=[-0.7326947  -1.17870136 -1.15467978  0.57104744  1.34756607 -1.17058616
 -0.70073144 -1.16937678]
Epoch=145, 	 E=0.3785,	 w=[-0.7329899  -1.17920081 -1.15642239  0.57058572  1.34652765 -1.17075125
 -0.70109239 -1.16968227]
Epoch=146, 	 E=0.3767,	 w=[-0.73328421 -1.17969909 -1.15816165  0.57012525  1.34549121 -1.17091601
 -0.70145231 -1.16998687]
Epoch=147, 	 E=0.3749,	 w=[-0.73357764 -1.18019619 -1.15989758  0.56966602  1.34445676 -1.17108046
 -0.7018112  -1.17029056]
Epoch=148, 	 E=0.3731,	 w=[-0.7338702  -1.18069212 -1.16163018  0.56920803  1.34342429 -1.17124459
 -0.70216908 -1.17059337]
Epoch=149, 	 E=0.3714,	 w=[-0.73416188 -1.18118689 -1.16335947  0.56875127  1.34239379 -1.1714084
 -0.70252594 -1.17089529]
Epoch=150, 	 E=0.3696,	 w=[-0.73445269 -1.1816805  -1.16508546  0.56829575  1.34136525 -1.17157189
 -0.70288179 -1.17119632]
Epoch=151, 	 E=0.3679,	 w=[-0.73474263 -1.18217296 -1.16680816  0.56784144  1.34033867 -1.17173507
 -0.70323664 -1.17149648]
Epoch=152, 	 E=0.3662,	 w=[-0.73503172 -1.18266427 -1.16852759  0.56738834  1.33931404 -1.17189794
 -0.70359048 -1.17179576]
Epoch=153, 	 E=0.3645,	 w=[-0.73531995 -1.18315443 -1.17024374  0.56693646  1.33829135 -1.1720605
 -0.70394334 -1.17209418]
Epoch=154, 	 E=0.3628,	 w=[-0.73560733 -1.18364346 -1.17195665  0.56648578  1.33727059 -1.17222275
 -0.7042952  -1.17239173]
Epoch=155, 	 E=0.3611,	 w=[-0.73589386 -1.18413136 -1.17366631  0.5660363   1.33625176 -1.17238469
 -0.70464608 -1.17268842]
Epoch=156, 	 E=0.3594,	 w=[-0.73617955 -1.18461812 -1.17537275  0.56558801  1.33523485 -1.17254632
 -0.70499598 -1.17298425]
Epoch=157, 	 E=0.3578,	 w=[-0.7364644  -1.18510377 -1.17707596  0.5651409   1.33421985 -1.17270764
 -0.7053449  -1.17327923]
Epoch=158, 	 E=0.3562,	 w=[-0.73674841 -1.18558829 -1.17877597  0.56469498  1.33320676 -1.17286867
 -0.70569285 -1.17357337]
Epoch=159, 	 E=0.3546,	 w=[-0.73703159 -1.1860717  -1.18047278  0.56425023  1.33219557 -1.17302938
 -0.70603984 -1.17386666]
Epoch=160, 	 E=0.353,	 w=[-0.73731395 -1.186554   -1.18216641  0.56380665  1.33118627 -1.1731898
 -0.70638587 -1.17415911]

In [ ]:
plt.plot(error_hist)

In [ ]:
X_train_minmax = np.hstack((np.ones((len(X_train_minmax), 1)), X_train_minmax))
print(X_train_minmax.shape)
Xtest_minmax = np.hstack((np.ones((len(X_test_minmax), 1)), X_test_minmax))
print(Xtest_minmax.shape)

(160, 13)
(40, 9)

In [ ]:
Xtest_minmax.shape

(40, 9)

In [ ]:
Xtest_minmax = np.hstack((np.ones((len(X_test_minmax), 1)), X_test_minmax))
# Xtest_minmax.shape

y_hat = logistic_regression(X_test_minmax, w)
accuracy(y_test, y_hat)

ValueError: operands could not be broadcast together with shapes (40,) (40,160)